version: "3.9"

services:
  db:
    container_name: postgres_quests
    image: postgres:16.2-alpine3.19
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "adminPG"
      POSTGRES_PASSWORD: "1Qwerty2$"
      POSTGRES_DB: "quests"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - postgres
  pgadmin:
    container_name: postgres_pgadmin
    image: dpage/pgadmin4:7.2
    environment:
      PGADMIN_DEFAULT_EMAIL: "pgadmin@quests.com"
      PGADMIN_DEFAULT_PASSWORD: "1Qwerty2$"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - postgres
volumes:
  habrdb-data:
  pgadmin-data:
networks:
  postgres:
    driver: bridge