// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/CompleteSteps": {
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Устанавливает признак выполнения шага у пользователя",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "history"
                ],
                "summary": "Выполнить шаг",
                "operationId": "CompleteSteps",
                "parameters": [
                    {
                        "description": "обновленная информация о шагах задания",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/storage.NewQuestSteps"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/storage.NewQuestStep"
                        }
                    }
                }
            }
        },
        "/CreateQuest": {
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Создает новое задание",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "quests"
                ],
                "summary": "Добавить задание",
                "operationId": "CreateQuest",
                "parameters": [
                    {
                        "description": "информация о задании",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/storage.NewQuest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/storage.NewQuest"
                        }
                    }
                }
            }
        },
        "/CreateQuestSteps": {
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Добавляет новые шаги к заданию",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "quests"
                ],
                "summary": "Добавить шаг к заданию",
                "operationId": "CreateQuestSteps",
                "parameters": [
                    {
                        "description": "информация о шагах задания",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/storage.NewQuestSteps"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/storage.NewQuestStep"
                        }
                    }
                }
            }
        },
        "/CreateUser": {
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Создает нового пользователя приложения",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Создать пользователя",
                "operationId": "CreateUser",
                "parameters": [
                    {
                        "description": "Информация о пользователе",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/users.User"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/DeleteUser": {
            "delete": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Удаляет пользователя приложения",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Удалить пользователя",
                "operationId": "DeleteUser",
                "parameters": [
                    {
                        "description": "Идентификатор пользователя",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/users.DeleteUserStruct"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/GetAllUsers": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Возвращает всех пользователей приложения",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "получить пользователей",
                "operationId": "GetAllUsers",
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/GetHistory": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Создает новое задание",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "history"
                ],
                "summary": "Обновить шаг к заданию",
                "operationId": "GetHistory",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/history.UserBonus"
                        }
                    }
                }
            }
        },
        "/GetQuests": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Создает новое задание",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "quests"
                ],
                "summary": "Обновить шаг к заданию",
                "operationId": "GetQuests",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/quest.Quests"
                        }
                    }
                }
            }
        },
        "/UpdateQuestSteps": {
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Создает новое задание",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "quests"
                ],
                "summary": "Обновить шаг к заданию",
                "operationId": "UpdateQuestSteps",
                "parameters": [
                    {
                        "description": "обновленная информация о шагах задания",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/storage.NewQuestSteps"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/storage.NewQuestStep"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "history.UserBonus": {
            "description": "UserBonus json для получения история выполнения заданий и их шагов",
            "type": "object",
            "properties": {
                "ComplitedQuests": {
                    "description": "Список заданий в которых участвовал пользователь",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/history.UserCompletedQuest"
                    }
                },
                "TotalBonus": {
                    "description": "Общий бонусный счет пользователя",
                    "type": "integer"
                }
            }
        },
        "history.UserCompletedQuest": {
            "type": "object",
            "properties": {
                "AllStepsCount": {
                    "description": "Кол-во шагов, доступное в задании",
                    "type": "integer"
                },
                "Bonus": {
                    "description": "Сумма Бонусов за выполненные задания",
                    "type": "integer"
                },
                "CompletedSteps": {
                    "description": "Выполненные шаги пользователем",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/history.UserCompletedSteps"
                    }
                },
                "CompletedStepsCount": {
                    "description": "Кол-во выполненных шагов заданий пользователем",
                    "type": "integer"
                },
                "QuestId": {
                    "description": "ИД задания",
                    "type": "string"
                },
                "QuestName": {
                    "description": "Имя выполненного задания пользователем",
                    "type": "string"
                }
            }
        },
        "history.UserCompletedSteps": {
            "type": "object",
            "properties": {
                "Count": {
                    "description": "Кол-во выполнений шага",
                    "type": "integer"
                },
                "StepName": {
                    "description": "Имя выполненного шага",
                    "type": "string"
                },
                "UserBonusStep": {
                    "description": "Бонус пользователя за выполнение шага",
                    "type": "integer"
                }
            }
        },
        "quest.Quests": {
            "description": "Quests json информация о заданиях и их шагов",
            "type": "object",
            "properties": {
                "Id": {
                    "description": "ИД задания",
                    "type": "string"
                },
                "QuestName": {
                    "description": "Имя выполненного задания пользователем",
                    "type": "string"
                },
                "Steps": {
                    "description": "Шаги задания",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/quest.Steps"
                    }
                }
            }
        },
        "quest.Steps": {
            "type": "object",
            "properties": {
                "Bonus": {
                    "description": "Бонус за выполнение шага",
                    "type": "integer"
                },
                "Id": {
                    "description": "ИД шага",
                    "type": "integer"
                },
                "StepName": {
                    "description": "Имя шага",
                    "type": "string"
                },
                "isMulti": {
                    "description": "Признак того, что шаг можно выполнять повторно",
                    "type": "boolean"
                }
            }
        },
        "storage.NewQuest": {
            "description": "NewQuest json для создания задания с шагами",
            "type": "object",
            "properties": {
                "Name": {
                    "description": "Имя задания",
                    "type": "string"
                },
                "QuestSteps": {
                    "description": "Шаги задания",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/storage.NewQuestStep"
                    }
                },
                "id": {
                    "description": "Идентификатор задания",
                    "type": "integer"
                }
            }
        },
        "storage.NewQuestStep": {
            "type": "object",
            "properties": {
                "Bonus": {
                    "description": "Бонус за задание",
                    "type": "integer"
                },
                "IsMulti": {
                    "description": "Признак того, что шаг можно выполнять несколько раз",
                    "type": "boolean"
                },
                "QuestId": {
                    "description": "Идентификатор задания. При создании методом CreateQuest, значение будет проигнорировано, т.к. будет подставляться идентификатор создаваемого задания",
                    "type": "integer"
                },
                "StepName": {
                    "description": "Описание шага",
                    "type": "string"
                },
                "id": {
                    "description": "Идентификатор задания",
                    "type": "integer"
                }
            }
        },
        "storage.NewQuestSteps": {
            "description": "NewQuestStep json для создания шага задания",
            "type": "object",
            "properties": {
                "QuestSteps": {
                    "description": "Идентификатор задания",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/storage.NewQuestStep"
                    }
                }
            }
        },
        "users.DeleteUserStruct": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                }
            }
        },
        "users.User": {
            "description": "User информация о пользователе",
            "type": "object",
            "properties": {
                "id": {
                    "description": "идентификатор пользователя",
                    "type": "integer"
                },
                "password": {
                    "description": "пароль пользователя",
                    "type": "string"
                },
                "userIsAdmin": {
                    "description": "признак того, что пользователь является администратором",
                    "type": "boolean"
                },
                "username": {
                    "description": "имя пользователя",
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BasicAuth": {
            "type": "basic"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Задания пользователей API",
	Description:      "Фильмотека",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
